### ISSUE TITLE
两个示例场景运行的时候会报错

### ISSUE THREAD

**Issue by PjLovePb** [wuxingogo/Unity-BezierArrow#1]
FileNotFoundException: Could not load file or assembly 'WuxingogoEditor' or one of its dependencies
System.AppDomain.Load (System.String assemblyString, System.Security.Policy.Evidence assemblySecurity, System.Boolean refonly) (at <fb001e01371b4adca20013e0ac763896>:0)
System.AppDomain.Load (System.String assemblyString) (at <fb001e01371b4adca20013e0ac763896>:0)
(wrapper remoting-invoke-with-check) System.AppDomain.Load(string)
wuxingogo.Reflection.XReflectionUtils.GetEditorAssembly () (at C:/Users/Thunder/Downloads/Wuxingogo2019-master/Runtime/Tools/XReflectionUtils.cs:103)
wuxingogo.Reflection.XReflectionUtils.GetEditorType (System.String typeName) (at C:/Users/Thunder/Downloads/Wuxingogo2019-master/Runtime/Tools/XReflectionUtils.cs:108)
wuxingogo.Reflection.XReflectionUtils.GetPrefabType (UnityEngine.Object asset) (at C:/Users/Thunder/Downloads/Wuxingogo2019-master/Runtime/Tools/XReflectionUtils.cs:405)
XBezierArrow2.InitMesh () (at Assets/Scripts/XBezierArrow2.cs:153)
XBezierArrow2.Refresh () (at Assets/Scripts/XBezierArrow2.cs:276)
XBezierArrow2.Update () (at Assets/Scripts/XBezierArrow2.cs:269)

**Comment by wuxingogo** [comment]
实在抱歉，该工程太老了，看起来是反射的方法没有找到，使用
https://github.com/wuxingogo/WuxingogoExtension2018 下的编辑器DLL和RuntimeDLL吧
将WuxingogoExtension 该文件夹下有两个DLL，拷贝到你工程下
或者你直接拷贝WuxingogoRuntime文件夹和WuxingogoEditor文件夹到你工程下也可以

**Comment by wuxingogo** [comment]
@PjLovePb 已经升级2019了，感谢您的关注。再有问题请及时沟通

**Comment by PjLovePb** [comment]
> 
多谢大佬回复，按照你写的做了之后运行RuntimeLoader场景之后还是会报错，
FileNotFoundException: Could not load file or assembly 'WuxingogoEditor' or one of its dependencies
System.AppDomain.Load (System.String assemblyString, System.Security.Policy.Evidence assemblySecurity, System.Boolean refonly) (at <fb001e01371b4adca20013e0ac763896>:0)
System.AppDomain.Load (System.String assemblyString) (at <fb001e01371b4adca20013e0ac763896>:0)
(wrapper remoting-invoke-with-check) System.AppDomain.Load(string)
wuxingogo.Reflection.XReflectionUtils.GetEditorAssembly () (at Packages/Wuxingogo2019/Runtime/Tools/XReflectionUtils.cs:103)
wuxingogo.Reflection.XReflectionUtils.GetEditorType (System.String typeName) (at Packages/Wuxingogo2019/Runtime/Tools/XReflectionUtils.cs:108)
wuxingogo.Reflection.XReflectionUtils.GetPrefabType (UnityEngine.Object asset) (at Packages/Wuxingogo2019/Runtime/Tools/XReflectionUtils.cs:405)
XBezierArrow.MeshSetup () (at Assets/Scripts/XBezierArrow.cs:219)
XBezierArrow.Refresh () (at Assets/Scripts/XBezierArrow.cs:40)
XBezierArrow.Update () (at Assets/Scripts/XBezierArrow.cs:32)

**Comment by wuxingogo** [comment]
@PjLovePb 搜索下XReflectionUtils，
将return AppDomain.CurrentDomain.Load( "WuxingogoEditor" ); 这一行改为
return AppDomain.CurrentDomain.Load( "Wuxingogo.Editor" ); 
抱歉，忘记提交这个工程了
